### ISSUE TITLE
(TK-004):Create key pair generation mechanism e5

### ISSUE THREAD

**Issue by NkwaTambe** [ADORSYS-GIS/webank-UserApp#7]
## Description

Implement a cryptographic key generation mechanism for user account registration. This will involve generating a pair of public and private keys, which will be used to securely identify and authenticate users within the banking system. The private key will remain securely stored on the user's device, while the public key will be shared with the Online Banking System (OBS) during the registration process.

## Requirements

- Generate a key pair (public and private keys).
- Store the keys securely on the user's device.
- Use the public key during registration with the OBS.

## Acceptance Criteria

- Key pairs are successfully generated and stored securely on the user's device.
- The public key is correctly utilized in the registration flow.

## Sub tickets

- [x] #37 
- [x] #38 
- [x] #39 
- [x] #40 

**Estimate:** 5

**Comment by francis-pouatcha** [comment]
Workshop with datave wallet team
- [ ] Generate a keypair 
- [ ] Hold the keypair in the web application
- [ ] Generate signed jwt, including a hash of the public key
- [ ] Send jwt as part of auth header
